name: 'Tomcat Deploy'

on:
  push:
    branches: [ deploy ]

jobs:
  Tomcat_Deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2

    - name: Replace Properties
      run: sh .github/workflows/replaceProperties.sh
      
    - name: Submodule Install
      run: sh .github/workflows/submoduleInstall.sh
          
    - name: Build War File
      run: mvn package

    - name: Copy ClassData
      run: sh .github/workflows/cpClassData.sh
            
    - name: Remove Old File
      run: echo ${{ secrets.PASSWORD }} | sudo -S rm -rf /var/lib/tomcat9/webapps/SpecialTopic*
      
    - name: Move New File
      run: echo ${{ secrets.PASSWORD }} | sudo -S cp target/SpcialTopic.war /var/lib/tomcat9/webapps/SpecialTopic.war

    - name: Sleep For 30 Seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'

    - name: Restore ClassData
      run: echo ${{ secrets.PASSWORD }} | sudo -S sh .github/workflows/rsClassData.sh